name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
      - name: scalafix
        run: sbt "src/scalafix --check"
      - name: scalafmt
        run: sbt scalafmtSbtCheck scalafmtCheckAll
      - name: Test
        run: sbt test