name: dependencies
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Scala Steward Github Action
        uses: scala-steward-org/scala-steward-action@v2.29.0
        with:
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}